"""Menu content generated by Qwen, with operational metadata attached by Python."""
from typing import Annotated, Literal
from pydantic import BaseModel, ConfigDict, Field

Nonempty = Annotated[str, Field(min_length=1)]
OptionalText = Nonempty | None
Price = Annotated[float, Field(ge=0)]
SourceIds = Annotated[list[Nonempty], Field(min_length=1)]


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", allow_inf_nan=False, strict=True)


class Evidence(StrictModel):
    source_id: Nonempty
    quote: Nonempty


class GroundedRecord(StrictModel):
    source_ids: SourceIds
    evidence: Annotated[list[Evidence], Field(min_length=1)]
    issues: list[str]


class MenuVariant(StrictModel):
    size: OptionalText
    temperature: Literal["hot", "iced"] | None
    price: Price | None
    price_note: OptionalText
    source_ids: SourceIds


class ModelProduct(GroundedRecord):
    name: Nonempty
    context: OptionalText
    aliases: list[Nonempty]
    category: OptionalText
    description: OptionalText
    variants: list[MenuVariant]
    series: list[Nonempty]
    search_text: Nonempty


class ModelSeries(GroundedRecord):
    name: Nonempty
    description: OptionalText
    price_claims: list[MenuVariant]


class AddonOffer(StrictModel):
    price: Price | None
    applies_to: list[Nonempty] | None
    source_ids: SourceIds


class ModelAddon(GroundedRecord):
    name: Nonempty
    offers: Annotated[list[AddonOffer], Field(min_length=1)]


class SourceNote(StrictModel):
    source_id: Nonempty
    notes: list[str]


class ModelMenu(StrictModel):
    """Only these fields are requested from the model."""
    products: list[ModelProduct]
    series: list[ModelSeries]
    addons: list[ModelAddon]
    source_notes: list[SourceNote]
    issues: list[str]


class MenuProduct(ModelProduct):
    product_id: Nonempty


class SourceRecord(StrictModel):
    source_id: Nonempty
    ocr_file: str
    ocr_sha256: str
    image_file: str
    image_sha256: str
    transcription: str
    ocr_uncertainties: list[str]


class Generation(StrictModel):
    method: Literal["qwen_batch"] = "qwen_batch"
    model: Nonempty
    model_digest: Nonempty
    prompt_version: Nonempty
    input_digest: Nonempty
    prompt_sha256: Nonempty
    response_sha256: Nonempty
    run_id: Nonempty
    run_directory: Nonempty
    attempt_count: int = Field(ge=1, le=2)
    generated_at: Nonempty
    duration_seconds: float = Field(ge=0)
    num_ctx: int = Field(gt=0)
    num_predict: int = Field(gt=0)
    metrics: dict[str, int]


class StructuredMenu(ModelMenu):
    """The sole final menu file; model content plus operational provenance."""
    schema_version: Literal[3] = 3
    status: Literal["draft"] = "draft"
    products: list[MenuProduct]
    generation: Generation
    currency: str | None
    currency_source: Literal["user_config", "unspecified"]
    source_count: int = Field(ge=0)
    product_count: int = Field(ge=0)
    sources: list[SourceRecord]
